@startuml
Main -> Mapper: map()
Mapper -> MappingRule: new
MappingRule -> Path: new
Path -> PathMatcher: new
PathMatcher -> PathMatcher: parse
Main -> Mapper: provide()
Mapper -> MappingRule: setTemplate()
Main -> Mapper: resolve()
Mapper -> MappingRule: resolve()
MappingRule -> Path: match()
Path -> PathMatcher: match()
MappingRule -> Resolved: new
MappingRule -> Mapper: Resolved
Mapper -> Resolved: ->template->call()
Mapper <- Resolved: route
Mapper -> Template: new & bind()
Template -> DataBinder: bind()
@enduml